POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NmYxNmRmM2M5NDhiNTAzZGUwMDYxNjMiLCJpYXQiOjE3MjcwOTg4NjF9.d36PdYE53lxq7tSXg65pDXSy0SQpKjg2civuruWkouw

{
    "title": "New blog #44",
    "author": "J.K Kennedy",
    "url": "www.kennedy.co",
    "likes": 10
}